import { CanvasElement } from '@/store/editor.store'

/**
 * Additional Premium Business Card Templates
 * More variety with different styles and layouts
 */

// 6. Corporate Navy
export const corporateNavy: CanvasElement[] = [
  // Background
  {
    id: 'bg_navy',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#1e3a8a',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Silver accent bar
  {
    id: 'bar_silver',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 15,
    fill: '#c0c0c0',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'CORPORATE\nSOLUTIONS',
    x: 80,
    y: 180,
    width: 600,
    height: 130,
    fontSize: 50,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 3,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Robert Wilson',
    x: 80,
    y: 400,
    width: 400,
    height: 45,
    fontSize: 26,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#c0c0c0',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Senior Consultant',
    x: 80,
    y: 455,
    width: 400,
    height: 32,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.9,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'robert@corporate.com | +91 98765 43210',
    x: 80,
    y: 510,
    width: 600,
    height: 28,
    fontSize: 13,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.8,
  },
]

// 7. Real Estate Elegant
export const realEstateElegant: CanvasElement[] = [
  // Background
  {
    id: 'bg_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Gold accent rectangle
  {
    id: 'rect_gold',
    type: 'shape',
    shapeType: 'rect',
    x: 700,
    y: 37.5,
    width: 387.5,
    height: 600,
    fill: '#d4af37',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.1,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'PREMIUM\nESTATES',
    x: 80,
    y: 160,
    width: 550,
    height: 140,
    fontSize: 54,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1f2937',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 4,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Luxury Real Estate',
    x: 80,
    y: 310,
    width: 400,
    height: 35,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#d4af37',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Emily Davis',
    x: 80,
    y: 420,
    width: 400,
    height: 45,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1f2937',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Real Estate Agent',
    x: 80,
    y: 475,
    width: 400,
    height: 32,
    fontSize: 15,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#6b7280',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'emily@premiumestates.com | +91 98765 43210',
    x: 80,
    y: 520,
    width: 650,
    height: 28,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#9ca3af',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
]

// 8. Medical Clean
export const medicalClean: CanvasElement[] = [
  // Background
  {
    id: 'bg_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Blue accent bar
  {
    id: 'bar_blue',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 20,
    height: 600,
    fill: '#0ea5e9',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Cross icon (medical symbol)
  {
    id: 'cross_vertical',
    type: 'shape',
    shapeType: 'rect',
    x: 850,
    y: 200,
    width: 15,
    height: 80,
    fill: '#0ea5e9',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 2,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.3,
  },
  {
    id: 'cross_horizontal',
    type: 'shape',
    shapeType: 'rect',
    x: 817.5,
    y: 232.5,
    width: 80,
    height: 15,
    fill: '#0ea5e9',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 2,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.3,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'HEALTHCARE\nCLINIC',
    x: 100,
    y: 170,
    width: 600,
    height: 130,
    fontSize: 50,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1e40af',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Dr. James Miller',
    x: 100,
    y: 400,
    width: 400,
    height: 45,
    fontSize: 26,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1f2937',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'General Physician',
    x: 100,
    y: 455,
    width: 400,
    height: 32,
    fontSize: 15,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#0ea5e9',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'dr.james@healthcare.com | +91 98765 43210',
    x: 100,
    y: 510,
    width: 650,
    height: 28,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#6b7280',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
]

// 9. QR Modern
export const qrModern: CanvasElement[] = [
  // Background
  {
    id: 'bg_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // QR Code placeholder
  {
    id: 'qr_bg',
    type: 'shape',
    shapeType: 'rect',
    x: 750,
    y: 150,
    width: 200,
    height: 200,
    fill: '#f3f4f6',
    stroke: '#e5e7eb',
    strokeWidth: 2,
    cornerRadius: 12,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // QR pattern (simplified)
  {
    id: 'qr_1',
    type: 'shape',
    shapeType: 'rect',
    x: 780,
    y: 180,
    width: 40,
    height: 40,
    fill: '#1f2937',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 4,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  {
    id: 'qr_2',
    type: 'shape',
    shapeType: 'rect',
    x: 880,
    y: 180,
    width: 40,
    height: 40,
    fill: '#1f2937',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 4,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  {
    id: 'qr_3',
    type: 'shape',
    shapeType: 'rect',
    x: 780,
    y: 280,
    width: 40,
    height: 40,
    fill: '#1f2937',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 4,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  {
    id: 'qr_4',
    type: 'shape',
    shapeType: 'rect',
    x: 880,
    y: 280,
    width: 40,
    height: 40,
    fill: '#1f2937',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 4,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'DIGITAL\nCONNECT',
    x: 80,
    y: 180,
    width: 550,
    height: 130,
    fontSize: 52,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1f2937',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 3,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Scan to Connect',
    x: 750,
    y: 370,
    width: 200,
    height: 30,
    fontSize: 13,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#3b82f6',
    align: 'center',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'David Chen',
    x: 80,
    y: 420,
    width: 400,
    height: 45,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#1f2937',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Digital Marketing Specialist',
    x: 80,
    y: 475,
    width: 450,
    height: 32,
    fontSize: 15,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#6b7280',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'david@digitalconnect.com | +91 98765 43210',
    x: 80,
    y: 520,
    width: 650,
    height: 28,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#9ca3af',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
]

// 10. Photography Studio
export const photographyStudio: CanvasElement[] = [
  // Background
  {
    id: 'bg_black',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#000000',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Image placeholder area
  {
    id: 'image_area',
    type: 'shape',
    shapeType: 'rect',
    x: 600,
    y: 37.5,
    width: 487.5,
    height: 600,
    fill: '#333333',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'STUDIO\nPHOTO',
    x: 80,
    y: 160,
    width: 450,
    height: 140,
    fontSize: 56,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 4,
    lineHeight: 1.05,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Professional Photography',
    x: 80,
    y: 310,
    width: 400,
    height: 35,
    fontSize: 14,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.7,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Lisa Anderson',
    x: 80,
    y: 420,
    width: 400,
    height: 45,
    fontSize: 26,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Professional Photographer',
    x: 80,
    y: 475,
    width: 400,
    height: 32,
    fontSize: 14,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.8,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'lisa@studiophoto.com | +91 98765 43210',
    x: 80,
    y: 520,
    width: 500,
    height: 28,
    fontSize: 11,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.7,
  },
]

export default {
  corporateNavy,
  realEstateElegant,
  medicalClean,
  qrModern,
  photographyStudio,
}
