import { CanvasElement } from '@/store/editor.store'

/**
 * Corporate Blue Business Card Template
 * Features: Modern corporate design with teal accent and wave logo
 */

export const corporateBlueTemplate: CanvasElement[] = [
  // Main White Background
  {
    id: 'bg_main_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },

  // Right Teal Section
  {
    id: 'bg_right_teal',
    type: 'shape',
    shapeType: 'rect',
    x: 637.5,
    y: 37.5,
    width: 450,
    height: 600,
    fill: '#4A90A4',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },

  // Logo Background Circle
  {
    id: 'logo_circle_bg',
    type: 'shape',
    shapeType: 'circle',
    x: 100,
    y: 150,
    width: 200,
    height: 200,
    fill: '#E8F4F8',
    stroke: '#4A90A4',
    strokeWidth: 3,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },

  // Logo Symbol Placeholder (Wave shape simulated with circle)
  {
    id: 'logo_wave',
    type: 'shape',
    shapeType: 'circle',
    x: 150,
    y: 200,
    width: 100,
    height: 100,
    fill: '#4A90A4',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 3,
    visible: true,
    locked: false,
  },

  // Company Name Text
  {
    id: 'text_company_name',
    type: 'text',
    text: 'COMPANY NAME',
    x: 100,
    y: 400,
    width: 450,
    height: 80,
    fontSize: 32,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#2C3E50',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 4,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Tagline Text
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Your Tagline',
    x: 100,
    y: 490,
    width: 450,
    height: 50,
    fontSize: 18,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#7F8C8D',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 1,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 5,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Full Name
  {
    id: 'text_full_name_right',
    type: 'text',
    text: 'Full Name',
    x: 680,
    y: 120,
    width: 350,
    height: 60,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 1,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 6,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Job Title
  {
    id: 'text_job_title_right',
    type: 'text',
    text: 'Job Title',
    x: 680,
    y: 190,
    width: 350,
    height: 50,
    fontSize: 20,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 7,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Email/Other
  {
    id: 'text_email_right',
    type: 'text',
    text: 'Email / Other',
    x: 680,
    y: 260,
    width: 350,
    height: 45,
    fontSize: 18,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 8,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Phone/Other
  {
    id: 'text_phone_right',
    type: 'text',
    text: 'Phone / Other',
    x: 680,
    y: 315,
    width: 350,
    height: 45,
    fontSize: 18,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 9,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Address Line 1
  {
    id: 'text_address1_right',
    type: 'text',
    text: 'Address Line 1',
    x: 680,
    y: 370,
    width: 350,
    height: 45,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 10,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Right Section - Address Line 2
  {
    id: 'text_address2_right',
    type: 'text',
    text: 'Address Line 2',
    x: 680,
    y: 425,
    width: 350,
    height: 45,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 11,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },
]

export default corporateBlueTemplate
