import { CanvasElement } from '@/store/editor.store'

// Simple default business card template
const defaultTemplate: CanvasElement[] = [
  // Company Name
  {
    id: 'default-company-name',
    type: 'text',
    text: '',
    x: 100,
    y: 80,
    width: 600,
    height: 80,
    fontSize: 48,
    fontFamily: 'Poppins',
    fontWeight: 700,
    fill: '#1F2937',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Full Name
  {
    id: 'default-full-name',
    type: 'text',
    text: '',
    x: 100,
    y: 180,
    width: 600,
    height: 50,
    fontSize: 32,
    fontFamily: 'Inter',
    fontWeight: 600,
    fill: '#3B82F6',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Job Title
  {
    id: 'default-job-title',
    type: 'text',
    text: '',
    x: 100,
    y: 240,
    width: 600,
    height: 40,
    fontSize: 20,
    fontFamily: 'Inter',
    fontWeight: 400,
    fill: '#6B7280',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Divider Line
  {
    id: 'default-divider',
    type: 'shape',
    shapeType: 'rect',
    x: 200,
    y: 300,
    width: 400,
    height: 2,
    fill: '#E5E7EB',
    stroke: 'none',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 1,
  },
  // Phone
  {
    id: 'default-phone',
    type: 'text',
    text: '',
    x: 100,
    y: 340,
    width: 600,
    height: 35,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: 400,
    fill: '#374151',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Email
  {
    id: 'default-email',
    type: 'text',
    text: '',
    x: 100,
    y: 385,
    width: 600,
    height: 35,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: 400,
    fill: '#374151',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Website
  {
    id: 'default-website',
    type: 'text',
    text: '',
    x: 100,
    y: 430,
    width: 600,
    height: 35,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: 400,
    fill: '#374151',
    align: 'center',
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
    zIndex: 2,
  },
  // Decorative Shape (Top Left)
  {
    id: 'default-shape-1',
    type: 'shape',
    shapeType: 'circle',
    x: 50,
    y: 30,
    width: 40,
    height: 40,
    fill: '#3B82F6',
    stroke: 'none',
    strokeWidth: 0,
    rotation: 0,
    opacity: 0.2,
    visible: true,
    locked: false,
    zIndex: 0,
  },
  // Decorative Shape (Bottom Right)
  {
    id: 'default-shape-2',
    type: 'shape',
    shapeType: 'circle',
    x: 710,
    y: 480,
    width: 40,
    height: 40,
    fill: '#3B82F6',
    stroke: 'none',
    strokeWidth: 0,
    rotation: 0,
    opacity: 0.2,
    visible: true,
    locked: false,
    zIndex: 0,
  },
]

export default defaultTemplate
