import { CanvasElement } from '@/store/editor.store'

/**
 * Medical Teal Business Card Template
 * Features: Medical caduceus symbol, orange and teal color scheme
 */

export const medicalTealTemplate: CanvasElement[] = [
  // Left Orange Section
  {
    id: 'bg_left_orange',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 350,
    height: 600,
    fill: '#FF8C42',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },

  // Right Teal Section
  {
    id: 'bg_right_teal',
    type: 'shape',
    shapeType: 'rect',
    x: 387.5,
    y: 37.5,
    width: 700,
    height: 600,
    fill: '#00A9A5',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },

  // White Circle for Logo
  {
    id: 'logo_circle_white',
    type: 'shape',
    shapeType: 'circle',
    x: 137.5,
    y: 187.5,
    width: 200,
    height: 200,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },

  // Medical Symbol Placeholder (Circle)
  {
    id: 'medical_symbol',
    type: 'shape',
    shapeType: 'circle',
    x: 187.5,
    y: 237.5,
    width: 100,
    height: 100,
    fill: '#00A9A5',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 3,
    visible: true,
    locked: false,
  },

  // Full Name Text
  {
    id: 'text_full_name',
    type: 'text',
    text: 'Full Name',
    x: 450,
    y: 120,
    width: 550,
    height: 80,
    fontSize: 48,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 1,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 4,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Job Title Text
  {
    id: 'text_job_title',
    type: 'text',
    text: 'Job Title',
    x: 450,
    y: 210,
    width: 550,
    height: 60,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 5,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Phone/Other Text
  {
    id: 'text_phone',
    type: 'text',
    text: 'Phone / Other',
    x: 450,
    y: 320,
    width: 550,
    height: 50,
    fontSize: 22,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 6,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Email/Other Text
  {
    id: 'text_email',
    type: 'text',
    text: 'Email / Other',
    x: 450,
    y: 380,
    width: 550,
    height: 50,
    fontSize: 22,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 7,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },
]

export default medicalTealTemplate
