import { CanvasElement } from '@/store/editor.store'

/**
 * Modern Green Business Card Template
 * Features: Green geometric logo, dark sidebar with contact info
 */

export const modernGreenTemplate: CanvasElement[] = [
  // Main White Background
  {
    id: 'bg_main_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#F5F5F5',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },

  // Right Dark Sidebar
  {
    id: 'sidebar_dark',
    type: 'shape',
    shapeType: 'rect',
    x: 687.5, // Right side
    y: 37.5,
    width: 400,
    height: 600,
    fill: '#2D3E2E',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },

  // Green Accent Bar (Top of sidebar)
  {
    id: 'accent_green_bar',
    type: 'shape',
    shapeType: 'rect',
    x: 687.5,
    y: 37.5,
    width: 400,
    height: 15,
    fill: '#7FB069',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },

  // Logo Circle Background
  {
    id: 'logo_circle',
    type: 'shape',
    shapeType: 'circle',
    x: 100,
    y: 100,
    width: 180,
    height: 180,
    fill: '#7FB069',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 3,
    visible: true,
    locked: false,
  },

  // Decorative Star Icon
  {
    id: 'decorative_star',
    type: 'icon',
    name: 'Star',
    svg: `<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <polygon points="12,2 15.09,8.26 22,9.27 17,14.14 18.18,21.02 12,17.77 5.82,21.02 7,14.14 2,9.27 8.91,8.26" fill="currentColor"/>
    </svg>`,
    x: 150,
    y: 150,
    width: 80,
    height: 80,
    fill: '#FFFFFF',
    stroke: 'none',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 4,
    visible: true,
    locked: false,
    opacity: 1,
  },

  // Company Name Text
  {
    id: 'text_company_name',
    type: 'text',
    text: 'COMPANY\nNAME',
    x: 80,
    y: 350,
    width: 500,
    height: 120,
    fontSize: 42,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#2D3E2E',
    align: 'center',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.3,
    rotation: 0,
    zIndex: 5,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Sidebar Contact Info - Full Name
  {
    id: 'sidebar_full_name',
    type: 'text',
    text: 'Full Name',
    x: 720,
    y: 100,
    width: 330,
    height: 50,
    fontSize: 20,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 6,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Sidebar Contact Info - Phone/Office
  {
    id: 'sidebar_phone',
    type: 'text',
    text: 'Phone / Office',
    x: 720,
    y: 160,
    width: 330,
    height: 40,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 7,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Sidebar Contact Info - Email/Other
  {
    id: 'sidebar_email',
    type: 'text',
    text: 'Email / Other',
    x: 720,
    y: 210,
    width: 330,
    height: 40,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 8,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Sidebar Contact Info - Address Line 1
  {
    id: 'sidebar_address1',
    type: 'text',
    text: 'Address Line1',
    x: 720,
    y: 260,
    width: 330,
    height: 40,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 9,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Sidebar Contact Info - Address Line 2
  {
    id: 'sidebar_address2',
    type: 'text',
    text: 'Address Line2',
    x: 720,
    y: 310,
    width: 330,
    height: 40,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 10,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },
]

export default modernGreenTemplate
