import { CanvasElement } from '@/store/editor.store'

/**
 * Premium Business Card Templates with Realistic Designs
 * Each template includes text, shapes, and professional layouts
 */

// 1. Modern Blue Professional
export const modernBlueProfessional: CanvasElement[] = [
  // Background
  {
    id: 'bg_main',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#1e40af',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Decorative Circle
  {
    id: 'circle_accent',
    type: 'shape',
    shapeType: 'circle',
    x: 850,
    y: 80,
    width: 150,
    height: 150,
    fill: '#fbbf24',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.3,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'YOUR COMPANY',
    x: 80,
    y: 150,
    width: 600,
    height: 80,
    fontSize: 48,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Professional Business Solutions',
    x: 80,
    y: 240,
    width: 500,
    height: 40,
    fontSize: 18,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.9,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'John Doe',
    x: 80,
    y: 400,
    width: 400,
    height: 50,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Chief Executive Officer',
    x: 80,
    y: 460,
    width: 400,
    height: 35,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#fbbf24',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact Info
  {
    id: 'text_contact',
    type: 'text',
    text: '+91 98765 43210 | john@company.com',
    x: 80,
    y: 520,
    width: 600,
    height: 30,
    fontSize: 14,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.8,
  },
]

// 2. Minimal White Elegant
export const minimalWhiteElegant: CanvasElement[] = [
  // Background
  {
    id: 'bg_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Thin accent line
  {
    id: 'line_accent',
    type: 'shape',
    shapeType: 'rect',
    x: 80,
    y: 200,
    width: 3,
    height: 80,
    fill: '#000000',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'MINIMAL',
    x: 120,
    y: 200,
    width: 500,
    height: 80,
    fontSize: 52,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#000000',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 8,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Design Studio',
    x: 120,
    y: 290,
    width: 400,
    height: 35,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#666666',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Jane Smith',
    x: 80,
    y: 420,
    width: 400,
    height: 40,
    fontSize: 24,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#000000',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'jane@minimal.com | +91 98765 43210',
    x: 80,
    y: 470,
    width: 500,
    height: 30,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#999999',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
]

// 3. Creative Gradient
export const creativeGradient: CanvasElement[] = [
  // Background Gradient (simulated with shapes)
  {
    id: 'bg_gradient_1',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#667eea',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  {
    id: 'bg_gradient_2',
    type: 'shape',
    shapeType: 'rect',
    x: 537.5,
    y: 37.5,
    width: 550,
    height: 600,
    fill: '#764ba2',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
    opacity: 0.7,
  },
  // Decorative Circle
  {
    id: 'circle_1',
    type: 'shape',
    shapeType: 'circle',
    x: 750,
    y: 100,
    width: 200,
    height: 200,
    fill: '#f093fb',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.2,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'CREATIVE\nSTUDIO',
    x: 80,
    y: 180,
    width: 600,
    height: 140,
    fontSize: 56,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 3,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Alex Johnson',
    x: 80,
    y: 400,
    width: 400,
    height: 45,
    fontSize: 26,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Creative Director',
    x: 80,
    y: 455,
    width: 400,
    height: 35,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.9,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'alex@creative.com | +91 98765 43210',
    x: 80,
    y: 510,
    width: 600,
    height: 30,
    fontSize: 13,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.85,
  },
]

// 4. Luxury Black Gold
export const luxuryBlackGold: CanvasElement[] = [
  // Background
  {
    id: 'bg_black',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#1a1a1a',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Gold accent line
  {
    id: 'line_gold',
    type: 'shape',
    shapeType: 'rect',
    x: 80,
    y: 250,
    width: 150,
    height: 3,
    fill: '#d4af37',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Logo Circle
  {
    id: 'logo_circle',
    type: 'shape',
    shapeType: 'circle',
    x: 450,
    y: 220,
    width: 160,
    height: 160,
    fill: 'transparent',
    stroke: '#d4af37',
    strokeWidth: 3,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'LUXURY',
    x: 80,
    y: 150,
    width: 500,
    height: 70,
    fontSize: 48,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#d4af37',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 6,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Tagline
  {
    id: 'text_tagline',
    type: 'text',
    text: 'Premium Services',
    x: 80,
    y: 270,
    width: 400,
    height: 35,
    fontSize: 16,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#d4af37',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.8,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Michael Brown',
    x: 80,
    y: 420,
    width: 400,
    height: 45,
    fontSize: 26,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Managing Director',
    x: 80,
    y: 475,
    width: 400,
    height: 30,
    fontSize: 14,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#d4af37',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'michael@luxury.com | +91 98765 43210',
    x: 80,
    y: 520,
    width: 600,
    height: 28,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.7,
  },
]

// 5. Modern Tech
export const modernTech: CanvasElement[] = [
  // Background
  {
    id: 'bg_dark',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#0f172a',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },
  // Cyan accent rectangle
  {
    id: 'rect_accent',
    type: 'shape',
    shapeType: 'rect',
    x: 700,
    y: 100,
    width: 250,
    height: 150,
    fill: '#06b6d4',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.15,
  },
  // Grid lines (decorative)
  {
    id: 'line_1',
    type: 'shape',
    shapeType: 'rect',
    x: 80,
    y: 350,
    width: 200,
    height: 2,
    fill: '#06b6d4',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.5,
  },
  {
    id: 'line_2',
    type: 'shape',
    shapeType: 'rect',
    x: 80,
    y: 380,
    width: 150,
    height: 2,
    fill: '#06b6d4',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
    opacity: 0.3,
  },
  // Company Name
  {
    id: 'text_company',
    type: 'text',
    text: 'TECH\nINNOVATIONS',
    x: 80,
    y: 150,
    width: 550,
    height: 140,
    fontSize: 52,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.1,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Name
  {
    id: 'text_name',
    type: 'text',
    text: 'Sarah Tech',
    x: 80,
    y: 420,
    width: 400,
    height: 45,
    fontSize: 28,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    fill: '#06b6d4',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
  // Position
  {
    id: 'text_position',
    type: 'text',
    text: 'Chief Technology Officer',
    x: 80,
    y: 475,
    width: 400,
    height: 32,
    fontSize: 15,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#ffffff',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
    opacity: 0.8,
  },
  // Contact
  {
    id: 'text_contact',
    type: 'text',
    text: 'sarah@techinnovations.com | +91 98765 43210',
    x: 80,
    y: 520,
    width: 650,
    height: 28,
    fontSize: 12,
    fontFamily: 'Arial',
    fontWeight: 'normal',
    fill: '#06b6d4',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },
]

export default {
  modernBlueProfessional,
  minimalWhiteElegant,
  creativeGradient,
  luxuryBlackGold,
  modernTech,
}
