import { CanvasElement } from '@/store/editor.store'

/**
 * Vintage Wood Business Card Template
 * Features: Wood texture background, tree logo, vintage style
 */

export const vintageWoodTemplate: CanvasElement[] = [
  // Wood Texture Background (simulated with beige color)
  {
    id: 'bg_wood_texture',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 600,
    fill: '#D4B896',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 0,
    visible: true,
    locked: false,
  },

  // Top White Banner
  {
    id: 'banner_top_white',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 37.5,
    width: 1050,
    height: 180,
    fill: '#FFFFFF',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 1,
    visible: true,
    locked: false,
  },

  // Bottom Dark Banner
  {
    id: 'banner_bottom_dark',
    type: 'shape',
    shapeType: 'rect',
    x: 37.5,
    y: 457.5,
    width: 1050,
    height: 180,
    fill: '#3E3E3E',
    stroke: 'transparent',
    strokeWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    zIndex: 2,
    visible: true,
    locked: false,
  },

  // Tree Logo Circle Background
  {
    id: 'logo_circle_tree',
    type: 'shape',
    shapeType: 'circle',
    x: 437.5,
    y: 237.5,
    width: 175,
    height: 175,
    fill: '#FFFFFF',
    stroke: '#3E3E3E',
    strokeWidth: 3,
    rotation: 0,
    zIndex: 3,
    visible: true,
    locked: false,
  },

  // Tree Symbol Placeholder (Circle)
  {
    id: 'tree_symbol',
    type: 'shape',
    shapeType: 'circle',
    x: 487.5,
    y: 287.5,
    width: 75,
    height: 75,
    fill: '#3E3E3E',
    stroke: 'transparent',
    strokeWidth: 0,
    rotation: 0,
    zIndex: 4,
    visible: true,
    locked: false,
  },

  // Top Banner - ESTD Text
  {
    id: 'text_estd',
    type: 'text',
    text: 'ESTD',
    x: 100,
    y: 70,
    width: 200,
    height: 50,
    fontSize: 24,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    fill: '#3E3E3E',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 5,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Top Banner - Year
  {
    id: 'text_year',
    type: 'text',
    text: '2026',
    x: 750,
    y: 70,
    width: 200,
    height: 50,
    fontSize: 24,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    fill: '#3E3E3E',
    align: 'right',
    verticalAlign: 'middle',
    letterSpacing: 2,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 6,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Top Banner - Company Name
  {
    id: 'text_company_name_top',
    type: 'text',
    text: 'COMPANY NAME',
    x: 200,
    y: 130,
    width: 650,
    height: 60,
    fontSize: 36,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    fill: '#3E3E3E',
    align: 'center',
    verticalAlign: 'middle',
    letterSpacing: 3,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 7,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Bottom Banner - Full Name
  {
    id: 'text_full_name_bottom',
    type: 'text',
    text: 'Full Name',
    x: 100,
    y: 480,
    width: 400,
    height: 50,
    fontSize: 24,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 1,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 8,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Bottom Banner - Job Title
  {
    id: 'text_job_title_bottom',
    type: 'text',
    text: 'Job Title',
    x: 100,
    y: 540,
    width: 400,
    height: 40,
    fontSize: 18,
    fontFamily: 'Georgia',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'left',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 9,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Bottom Banner - Phone/Other
  {
    id: 'text_phone_bottom',
    type: 'text',
    text: 'Phone / Other',
    x: 550,
    y: 490,
    width: 450,
    height: 40,
    fontSize: 18,
    fontFamily: 'Georgia',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'right',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 10,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },

  // Bottom Banner - Email/Other
  {
    id: 'text_email_bottom',
    type: 'text',
    text: 'Email / Other',
    x: 550,
    y: 540,
    width: 450,
    height: 40,
    fontSize: 18,
    fontFamily: 'Georgia',
    fontWeight: 'normal',
    fill: '#FFFFFF',
    align: 'right',
    verticalAlign: 'middle',
    letterSpacing: 0,
    lineHeight: 1.2,
    rotation: 0,
    zIndex: 11,
    visible: true,
    locked: false,
    padding: { horizontal: 12, vertical: 8 },
  },
]

export default vintageWoodTemplate
