import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Template, TemplateDocument, TemplateCategory } from './schemas/template.schema';
import { CreateTemplateDto } from './dto/create-template.dto';

// QR block: shows img when qrCodeUrl is set, bordered placeholder otherwise
const qrBlock = (color: string) =>
  `<div style="position:relative;width:48px;height:48px;flex-shrink:0;">` +
  `<div style="width:48px;height:48px;border:2px dashed ${color};border-radius:6px;opacity:0.5;position:absolute;inset:0;"></div>` +
  `<img src="{{qrCodeUrl}}" alt="QR" style="width:48px;height:48px;border-radius:6px;position:absolute;inset:0;object-fit:cover;" onerror="this.style.display='none'" />` +
  `</div>`;

//  Template HTML Definitions (20 templates, 5 style groups  4 each) 

const TEMPLATES_HTML = {

  // 
  // GROUP 1: MINIMAL CLEAN (category: minimal)
  // 

  // 1. Minimal White
  minimalWhiteFront: `<div style="width:100%;height:100%;background:#ffffff;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;border-left:4px solid #2563EB;"><div style="position:absolute;top:-20px;right:-20px;width:80px;height:80px;border-radius:50%;background:#eff6ff;"></div><div><div style="font-size:17px;font-weight:800;color:#111827;letter-spacing:-0.5px;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:#2563EB;margin-top:3px;font-weight:500;text-transform:uppercase;letter-spacing:1px;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#374151;margin-top:10px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#6b7280;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#6b7280;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#6b7280;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#6b7280;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  minimalWhiteBack: `<div style="width:100%;height:100%;background:#f8fafc;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;border-left:4px solid #2563EB;"><div style="font-size:15px;font-weight:800;color:#111827;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:#2563EB;border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#6b7280;"> {{phone}}</div><div style="font-size:9px;color:#6b7280;"> {{email}}</div><div style="font-size:9px;color:#6b7280;"> {{website}}</div><div style="font-size:9px;color:#6b7280;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 2. Slate Clean
  slateCleanFront: `<div style="width:100%;height:100%;background:#f1f5f9;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#475569,#94a3b8);"></div><div style="position:absolute;bottom:-30px;right:-30px;width:100px;height:100px;border-radius:50%;background:#e2e8f0;"></div><div><div style="font-size:17px;font-weight:800;color:#0f172a;letter-spacing:-0.3px;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:#64748b;margin-top:3px;font-style:italic;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#334155;margin-top:10px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#475569;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#475569;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#475569;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#475569;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  slateCleanBack: `<div style="width:100%;height:100%;background:#e2e8f0;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;"><div style="position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#475569,#94a3b8);"></div><div style="font-size:15px;font-weight:800;color:#0f172a;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:#475569;border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#475569;"> {{phone}}</div><div style="font-size:9px;color:#475569;"> {{email}}</div><div style="font-size:9px;color:#475569;"> {{website}}</div><div style="font-size:9px;color:#475569;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 3. Ivory Soft
  ivorySoftFront: `<div style="width:100%;height:100%;background:#fffbf0;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;bottom:0;right:0;width:3px;background:#d97706;"></div><div style="position:absolute;top:-15px;left:-15px;width:60px;height:60px;border-radius:50%;background:#fef3c7;opacity:0.8;"></div><div><div style="font-size:17px;font-weight:800;color:#1c1917;letter-spacing:-0.3px;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:#d97706;margin-top:3px;font-weight:500;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#44403c;margin-top:10px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  ivorySoftBack: `<div style="width:100%;height:100%;background:#fef9ee;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;"><div style="position:absolute;top:0;bottom:0;right:0;width:3px;background:#d97706;"></div><div style="font-size:15px;font-weight:800;color:#1c1917;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:#d97706;border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#78716c;"> {{phone}}</div><div style="font-size:9px;color:#78716c;"> {{email}}</div><div style="font-size:9px;color:#78716c;"> {{website}}</div><div style="font-size:9px;color:#78716c;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 4. Paper Light
  paperLightFront: `<div style="width:100%;height:100%;background:#fafaf9;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;border:1px solid #e7e5e4;"><div style="position:absolute;top:0;left:0;width:100%;height:3px;background:#6366f1;"></div><div style="position:absolute;bottom:-20px;right:-20px;width:70px;height:70px;border-radius:50%;background:#ede9fe;opacity:0.6;"></div><div><div style="font-size:17px;font-weight:800;color:#1c1917;letter-spacing:-0.3px;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:#6366f1;margin-top:3px;font-weight:500;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#44403c;margin-top:10px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#78716c;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  paperLightBack: `<div style="width:100%;height:100%;background:#fafaf9;font-family:'Inter',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;border:1px solid #e7e5e4;"><div style="position:absolute;top:0;left:0;width:100%;height:3px;background:#6366f1;"></div><div style="font-size:15px;font-weight:800;color:#1c1917;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:#6366f1;border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#78716c;"> {{phone}}</div><div style="font-size:9px;color:#78716c;"> {{email}}</div><div style="font-size:9px;color:#78716c;"> {{website}}</div><div style="font-size:9px;color:#78716c;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 
  // GROUP 2: GRADIENT MODERN (category: creative)
  // 

  // 5. Violet Gradient
  violetGradientFront: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:-30px;right:-30px;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,0.12);"></div><div style="position:absolute;bottom:-20px;left:-20px;width:80px;height:80px;border-radius:50%;background:rgba(255,255,255,0.08);"></div><div><div style="font-size:17px;font-weight:800;color:#ffffff;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:rgba(255,255,255,0.75);margin-top:3px;font-style:italic;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:rgba(255,255,255,0.9);margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,0.2);">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:rgba(255,255,255,0.85);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.85);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.85);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.85);display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  violetGradientBack: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#764ba2 0%,#667eea 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;overflow:hidden;"><div style="position:absolute;top:-40px;left:-40px;width:150px;height:150px;border-radius:50%;background:rgba(255,255,255,0.06);"></div><div style="font-size:15px;font-weight:800;color:#ffffff;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:rgba(255,255,255,0.6);border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:rgba(255,255,255,0.8);"> {{phone}}</div><div style="font-size:9px;color:rgba(255,255,255,0.8);"> {{email}}</div><div style="font-size:9px;color:rgba(255,255,255,0.8);"> {{website}}</div><div style="font-size:9px;color:rgba(255,255,255,0.8);text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 6. Ocean Gradient
  oceanGradientFront: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#0369a1 0%,#0891b2 50%,#06b6d4 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:-20px;right:-20px;width:100px;height:100px;border-radius:50%;background:rgba(255,255,255,0.1);"></div><div style="position:absolute;bottom:10px;left:-10px;width:60px;height:60px;border-radius:50%;background:rgba(255,255,255,0.07);"></div><div><div style="font-size:17px;font-weight:800;color:#ffffff;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:#bae6fd;margin-top:3px;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#e0f2fe;margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,0.25);">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#e0f2fe;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#e0f2fe;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#e0f2fe;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#e0f2fe;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  oceanGradientBack: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#06b6d4 0%,#0891b2 50%,#0369a1 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;overflow:hidden;"><div style="position:absolute;top:-30px;right:-30px;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,0.07);"></div><div style="font-size:15px;font-weight:800;color:#ffffff;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:#fbbf24;border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#bae6fd;"> {{phone}}</div><div style="font-size:9px;color:#bae6fd;"> {{email}}</div><div style="font-size:9px;color:#bae6fd;"> {{website}}</div><div style="font-size:9px;color:#bae6fd;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 7. Sunset Gradient
  sunsetGradientFront: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#f97316 0%,#ec4899 50%,#a855f7 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:-25px;right:-25px;width:100px;height:100px;border-radius:50%;background:rgba(255,255,255,0.12);"></div><div style="position:absolute;bottom:-15px;left:-15px;width:70px;height:70px;border-radius:50%;background:rgba(255,255,255,0.08);"></div><div><div style="font-size:17px;font-weight:800;color:#ffffff;line-height:1.2;text-shadow:0 1px 3px rgba(0,0,0,0.2);">{{businessName}}</div><div style="font-size:9px;color:rgba(255,255,255,0.8);margin-top:3px;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:rgba(255,255,255,0.95);margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,0.25);">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:rgba(255,255,255,0.9);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.9);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.9);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.9);display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  sunsetGradientBack: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#a855f7 0%,#ec4899 50%,#f97316 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;overflow:hidden;"><div style="position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,0.08);"></div><div style="font-size:15px;font-weight:800;color:#ffffff;text-align:center;text-shadow:0 1px 3px rgba(0,0,0,0.2);">{{businessName}}</div><div style="width:40px;height:2px;background:rgba(255,255,255,0.7);border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:rgba(255,255,255,0.85);"> {{phone}}</div><div style="font-size:9px;color:rgba(255,255,255,0.85);"> {{email}}</div><div style="font-size:9px;color:rgba(255,255,255,0.85);"> {{website}}</div><div style="font-size:9px;color:rgba(255,255,255,0.85);text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 8. Aurora Gradient
  auroraGradientFront: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#10b981 0%,#3b82f6 50%,#8b5cf6 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:-20px;right:-20px;width:90px;height:90px;border-radius:50%;background:rgba(255,255,255,0.1);"></div><div style="position:absolute;bottom:-10px;left:-10px;width:60px;height:60px;border-radius:50%;background:rgba(255,255,255,0.07);"></div><div><div style="font-size:17px;font-weight:800;color:#ffffff;line-height:1.2;">{{businessName}}</div><div style="font-size:9px;color:rgba(255,255,255,0.75);margin-top:3px;letter-spacing:0.5px;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:rgba(255,255,255,0.9);margin-top:10px;padding-top:10px;border-top:1px solid rgba(255,255,255,0.2);">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:rgba(255,255,255,0.88);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.88);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.88);display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:rgba(255,255,255,0.88);display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  auroraGradientBack: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#8b5cf6 0%,#3b82f6 50%,#10b981 100%);font-family:'Poppins',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;overflow:hidden;"><div style="position:absolute;top:-30px;left:-30px;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,0.06);"></div><div style="font-size:15px;font-weight:800;color:#ffffff;text-align:center;">{{businessName}}</div><div style="width:40px;height:2px;background:rgba(255,255,255,0.6);border-radius:2px;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:rgba(255,255,255,0.82);"> {{phone}}</div><div style="font-size:9px;color:rgba(255,255,255,0.82);"> {{email}}</div><div style="font-size:9px;color:rgba(255,255,255,0.82);"> {{website}}</div><div style="font-size:9px;color:rgba(255,255,255,0.82);text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 
  // GROUP 3: DARK PREMIUM (category: professional)
  // 

  // 9. Matte Black
  matteBlackFront: `<div style="width:100%;height:100%;background:#0f0f0f;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;right:0;width:3px;height:100%;background:linear-gradient(to bottom,#f59e0b,#d97706);"></div><div style="position:absolute;top:0;right:0;width:60px;height:60px;background:linear-gradient(135deg,#f59e0b,transparent);opacity:0.1;clip-path:polygon(100% 0,0 0,100% 100%);"></div><div><div style="font-size:16px;font-weight:800;color:#ffffff;letter-spacing:0.5px;text-transform:uppercase;line-height:1.2;">{{businessName}}</div><div style="font-size:8px;color:#f59e0b;margin-top:4px;letter-spacing:2px;text-transform:uppercase;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#d1d5db;margin-top:12px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#f59e0b;"></span><span>{{phone}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#f59e0b;"></span><span>{{email}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#f59e0b;"></span><span>{{website}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#f59e0b;"></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  matteBlackBack: `<div style="width:100%;height:100%;background:#0f0f0f;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;"><div style="position:absolute;top:0;right:0;width:3px;height:100%;background:linear-gradient(to bottom,#f59e0b,#d97706);"></div><div style="font-size:15px;font-weight:800;color:#ffffff;text-align:center;letter-spacing:0.5px;text-transform:uppercase;">{{businessName}}</div><div style="width:40px;height:1px;background:#f59e0b;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#9ca3af;"> {{phone}}</div><div style="font-size:9px;color:#9ca3af;"> {{email}}</div><div style="font-size:9px;color:#9ca3af;"> {{website}}</div><div style="font-size:9px;color:#9ca3af;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 10. Dark Gold
  darkGoldFront: `<div style="width:100%;height:100%;background:#1a1200;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#ffd700,#f59e0b,#ffd700);"></div><div style="position:absolute;bottom:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#ffd700,#f59e0b,#ffd700);"></div><div style="position:absolute;top:-30px;right:-30px;width:100px;height:100px;border-radius:50%;background:rgba(255,215,0,0.05);"></div><div><div style="font-size:16px;font-weight:800;color:#ffd700;letter-spacing:0.5px;line-height:1.2;">{{businessName}}</div><div style="font-size:8px;color:#d97706;margin-top:4px;letter-spacing:1.5px;text-transform:uppercase;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#e5e7eb;margin-top:12px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#d1d5db;display:flex;align-items:flex-start;gap:5px;"><span style="color:#ffd700;"></span><span>{{phone}}</span></div><div style="font-size:10px;color:#d1d5db;display:flex;align-items:flex-start;gap:5px;"><span style="color:#ffd700;"></span><span>{{email}}</span></div><div style="font-size:10px;color:#d1d5db;display:flex;align-items:flex-start;gap:5px;"><span style="color:#ffd700;"></span><span>{{website}}</span></div><div style="font-size:10px;color:#d1d5db;display:flex;align-items:flex-start;gap:5px;"><span style="color:#ffd700;"></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  darkGoldBack: `<div style="width:100%;height:100%;background:#1a1200;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;"><div style="position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#ffd700,#f59e0b,#ffd700);"></div><div style="position:absolute;bottom:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#ffd700,#f59e0b,#ffd700);"></div><div style="font-size:15px;font-weight:800;color:#ffd700;text-align:center;letter-spacing:0.5px;">{{businessName}}</div><div style="width:40px;height:1px;background:#ffd700;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#d1d5db;"> {{phone}}</div><div style="font-size:9px;color:#d1d5db;"> {{email}}</div><div style="font-size:9px;color:#d1d5db;"> {{website}}</div><div style="font-size:9px;color:#d1d5db;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 11. Obsidian
  obsidianFront: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;left:0;width:4px;height:100%;background:linear-gradient(to bottom,#818cf8,#6366f1);"></div><div style="position:absolute;top:-20px;right:-20px;width:80px;height:80px;border-radius:50%;background:rgba(99,102,241,0.15);"></div><div><div style="font-size:16px;font-weight:800;color:#e0e7ff;letter-spacing:0.3px;line-height:1.2;">{{businessName}}</div><div style="font-size:8px;color:#818cf8;margin-top:4px;letter-spacing:1.5px;text-transform:uppercase;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#c7d2fe;margin-top:12px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#a5b4fc;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{phone}}</span></div><div style="font-size:10px;color:#a5b4fc;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{email}}</span></div><div style="font-size:10px;color:#a5b4fc;display:flex;align-items:flex-start;gap:5px;"><span></span><span>{{website}}</span></div><div style="font-size:10px;color:#a5b4fc;display:flex;align-items:flex-start;gap:5px;"><span></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  obsidianBack: `<div style="width:100%;height:100%;background:linear-gradient(135deg,#16213e 0%,#1a1a2e 100%);font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;"><div style="position:absolute;top:0;left:0;width:4px;height:100%;background:linear-gradient(to bottom,#818cf8,#6366f1);"></div><div style="font-size:15px;font-weight:800;color:#e0e7ff;text-align:center;letter-spacing:0.3px;">{{businessName}}</div><div style="width:40px;height:1px;background:#818cf8;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#a5b4fc;"> {{phone}}</div><div style="font-size:9px;color:#a5b4fc;"> {{email}}</div><div style="font-size:9px;color:#a5b4fc;"> {{website}}</div><div style="font-size:9px;color:#a5b4fc;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

  // 12. Charcoal Elite
  charcoalEliteFront: `<div style="width:100%;height:100%;background:#1c1c1c;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;"><div style="position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#10b981,#059669);"></div><div style="position:absolute;bottom:-25px;right:-25px;width:90px;height:90px;border-radius:50%;background:rgba(16,185,129,0.08);"></div><div><div style="font-size:16px;font-weight:800;color:#f9fafb;letter-spacing:0.3px;line-height:1.2;">{{businessName}}</div><div style="font-size:8px;color:#10b981;margin-top:4px;letter-spacing:1.5px;text-transform:uppercase;">{{tagline}}</div><div style="font-size:12px;font-weight:600;color:#d1d5db;margin-top:12px;">{{name}}</div></div><div style="display:flex;flex-direction:column;gap:3px;"><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#10b981;"></span><span>{{phone}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#10b981;"></span><span>{{email}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#10b981;"></span><span>{{website}}</span></div><div style="font-size:10px;color:#9ca3af;display:flex;align-items:flex-start;gap:5px;"><span style="color:#10b981;"></span><span style="white-space:normal;word-break:break-word;font-size:10px;">{{address}}</span></div></div></div>`,

  charcoalEliteBack: `<div style="width:100%;height:100%;background:#1c1c1c;font-family:'Montserrat',sans-serif;padding:20px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;position:relative;"><div style="position:absolute;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,#10b981,#059669);"></div><div style="font-size:15px;font-weight:800;color:#f9fafb;text-align:center;letter-spacing:0.3px;">{{businessName}}</div><div style="width:40px;height:1px;background:#10b981;"></div><div style="display:flex;flex-direction:column;gap:4px;align-items:center;"><div style="font-size:9px;color:#9ca3af;"> {{phone}}</div><div style="font-size:9px;color:#9ca3af;"> {{email}}</div><div style="font-size:9px;color:#9ca3af;"> {{website}}</div><div style="font-size:9px;color:#9ca3af;text-align:center;white-space:normal;word-break:break-word;max-width:180px;"> {{address}}</div></div><div style="margin-top:4px;">QRPLACEHOLDER</div></div>`,

